[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# Environment variables should be set in Netlify Dashboard
# Go to Site Settings -> Environment Variables and add:
# REACT_APP_NOWPAYMENTS_API_KEY
# REACT_APP_ADMIN_ROUTE
# REACT_APP_ENVIRONMENT

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.nowpayments.io https://*.firebaseio.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.nowpayments.io https://*.firebaseio.com; font-src 'self' data:;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling
# [[forms]]
#   name = "contact"
#   action = "/contact"
#   method = "POST"

# Function for payment processing (if needed)
# [[functions]]
#   directory = "netlify/functions"

# Plugin configuration (disabled for now)
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"

# Build optimization (deprecated syntax removed)
# Note: Modern Netlify handles build optimization automatically
# Legacy build.processing configuration has been removed